  - name: "update repositorios"
    apt: update_cache=yes

  - name: "install common packages debian/ubuntu"
    apt: pkg={{ item }} state=latest
    with_items:
      - build-essential
      - git
      - supervisor
      - pkg-config