# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.box = "ubuntu/trusty64"
    wordpress.vm.network "private_network", ip: "192.168.33.10"

    wordpress.vm.provision "ansible" do |ansible|
      ansible.playbook = "blog.yml"
      #ansible.verbose = "vvv"
    end
  end

  config.vm.provider "virtualbox" do |vb|

    vb.customize ["modifyvm", :id, "--memory", "2048"]
  # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  # Customize the amount of memory on the VM:
  end

end
